apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namePrefix: dev-

namespace: dev

resources:
- ns.yaml
- ../../base

images:
- name: us-central1-docker.pkg.dev/maugram-dev/sampleapp1/sampleapp1
  newName: us-central1-docker.pkg.dev/maugram-dev/sampleapp1/sampleapp1
  newTag: 20220317-fail1
