apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namePrefix: dev-

namespace: dev

resources:
- ../../base
- ns.yaml

patchesStrategicMerge:
- sa.yaml

images:
- name: us-central1-docker.pkg.dev/maugram-dev/sampleapp1/sampleapp1
  newName: us-central1-docker.pkg.dev/maugram-dev/sampleapp1/sampleapp1
  newTag: 20220223-1
