apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      terminationGracePeriodSeconds: 5
      serviceAccountName: myapp-ksa
      containers:
        - name: server
          image: us-central1-docker.pkg.dev/maugram-dev/sampleapp1/sampleapp1
          ports:
            - containerPort: 80
          env:
            - name: DUMMY
              value: 100
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 5m
              memory: 32Mi
