apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      serviceAccountName: myapp-ksa
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: us-central1-docker.pkg.dev/maugram-dev/sampleapp1/sampleapp1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 101m
              memory: 128Mi
