# customChecks defines custom checks.
#customChecks:
#- name: "required-label-app"
#  template: "required-label"
#  params:
#    key: "app"
checks:
  # if doNotAutoAddDefaults is true, default checks are not automatically added.
  #doNotAutoAddDefaults: false

  # addAllBuiltIn, if set, adds all built-in checks. This allows users to
  # explicitly opt-out of checks that are not relevant using Exclude.
  # Takes precedence over doNotAutoAddDefaults, if both are set.
  #addAllBuiltIn: false

  # include explicitly adds checks, by name. You can reference any of the built-in checks.
  # Note that customChecks defined above are included automatically.
  #include:
  #- "required-label-owner"
  # exclude explicitly excludes checks, by name. exclude has the highest priority: if a check is
  # in exclude, then it is not considered, even if it is in include as well.
  exclude:
    # 後ほど対応
    - "run-as-non-root"

    # コンテナ内のバイナリやソースコードが改変・実行されることを防ぐためのものだが、
    # アプリケーションの対応コストが大きいため一旦無しとしておく
    - "no-read-only-root-fs"

    - "unset-cpu-requirements"
    - "unset-memory-requirements"
