name: k8s Yaml Lint

on:
  pull_request:
    paths:
      - 'k8s/**/*.yaml'
  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.3
      - name: install kube-linter
        id: install-kube-linter
        run: go install golang.stackrox.io/kube-linter/cmd/kube-linter@latest
      - name: lint
        id: lint
        run: ./scripts/ci/kube-linter.sh
