name: k8s Yaml Validate

on:
  pull_request:
    paths:
      - 'k8s/**/*.yaml'
  workflow_dispatch:

jobs:
  lint:
    name: validation and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.3
      - name: install kubeconform
        run: go install github.com/yannh/kubeconform/cmd/kubeconform@latest
      - name: validate
        id: validate
        run: ./scripts/ci/kubeconform.sh
