name: k8s Yaml Validate

on:
  pull_request:
    paths:
      - 'k8s/**/*.yaml'
  workflow_dispatch:

jobs:
  lint:
    name: validation and lint
env:
  KUBECONFORM_VERSION: 'v0.6.1'

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-kubeconform-go-install-cache-${{ env.KUBECONFORM_VERSION }}
          restore-keys: |
            ${{ runner.os }}-kubeconform-go-install-cache-${{ env.KUBECONFORM_VERSION }}
      - name: setup golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.3
      - name: install kubeconform
        run: go install github.com/yannh/kubeconform/cmd/kubeconform@${KUBECONFORM_VERSION}
      - name: validate
        id: validate
        run: ./scripts/ci/kubeconform.sh
